name: Bug report
description: Report a reproducible problem in MZmine
labels:
  - type:bug
  - needs-triage
title: "[Bug]: "
body:
  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction steps
      description: Provide clear, minimal steps to reproduce the issue.
      placeholder: |
        1. Go to ...
        2. Click ...
        3. Run ...
        4. See error
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What did you expect to happen?
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual behavior / logs
      description: What actually happened? Include stack traces or relevant logs.
      render: shell
    validations:
      required: true
  - type: input
    id: mzmine_version
    attributes:
      label: MZmine version/build
      description: Example "4.7.33" or commit SHA / nightly build info.
      placeholder: 4.7.33
    validations:
      required: true
  - type: input
    id: java_version
    attributes:
      label: Java version
      description: Output of `java -version`.
      placeholder: e.g., OpenJDK 17.0.10
    validations:
      required: true
  - type: dropdown
    id: os
    attributes:
      label: Operating system
      multiple: false
      options:
        - macOS
        - Windows
        - Linux
    validations:
      required: true
