{
  "formatVersion": "1.1",
  "component": {
    "group": "io.mzio",
    "module": "mzmine-core",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "mzmine-core-1.0.0.jar",
          "url": "mzmine-core-1.0.0.jar",
          "size": 19376,
          "sha512": "df92a077b28192fee895fe27b36a9a8fe249bfd699e5dac10d6f9f1bda84f41a07452077356cb79244627060a746ce28fe71e1c5f999fc67d6e28b19a20a933f",
          "sha256": "998ab7d0fad61a73fbe805dd94837eb86798433a46f04754c560e5a04b76ad11",
          "sha1": "5b593b9d26f96bcc53e68c2a3d11b55ffb7f62bf",
          "md5": "ea0e157f46bdff527e5df6391a87ef35"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "22.0.0"
          }
        },
        {
          "group": "org.controlsfx",
          "module": "controlsfx",
          "version": {
            "requires": "11.2.2"
          }
        },
        {
          "group": "org.kordamp.ikonli",
          "module": "ikonli-javafx",
          "version": {
            "requires": "12.3.1"
          }
        },
        {
          "group": "org.kordamp.ikonli",
          "module": "ikonli-bootstrapicons-pack",
          "version": {
            "requires": "12.3.1"
          }
        },
        {
          "group": "org.kordamp.ikonli",
          "module": "ikonli-lineawesome-pack",
          "version": {
            "requires": "12.3.1"
          }
        },
        {
          "group": "commons-cli",
          "module": "commons-cli",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "com.vdurmont",
          "module": "semver4j",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "io.mzio",
          "module": "user-management",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "io.mzio",
          "module": "user-client",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "io.github.mzmine",
          "module": "utils"
        },
        {
          "group": "org.openjfx",
          "module": "javafx-base",
          "version": {
            "requires": "24.0.2"
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-graphics",
          "version": {
            "requires": "24.0.2"
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-controls",
          "version": {
            "requires": "24.0.2"
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-fxml",
          "version": {
            "requires": "24.0.2"
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-swing",
          "version": {
            "requires": "24.0.2"
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-web",
          "version": {
            "requires": "24.0.2"
          }
        }
      ],
      "files": [
        {
          "name": "mzmine-core-1.0.0.jar",
          "url": "mzmine-core-1.0.0.jar",
          "size": 19376,
          "sha512": "df92a077b28192fee895fe27b36a9a8fe249bfd699e5dac10d6f9f1bda84f41a07452077356cb79244627060a746ce28fe71e1c5f999fc67d6e28b19a20a933f",
          "sha256": "998ab7d0fad61a73fbe805dd94837eb86798433a46f04754c560e5a04b76ad11",
          "sha1": "5b593b9d26f96bcc53e68c2a3d11b55ffb7f62bf",
          "md5": "ea0e157f46bdff527e5df6391a87ef35"
        }
      ]
    }
  ]
}
